# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/noiron/f6be6840739c7c0fc356659d64db96fc
          gist_title: traverseFolderList.js
          gist_description: traverseFolderList
          github_file: traverseFolderList.js
      
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync1
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/noiron/f6be6840739c7c0fc356659d64db96fc
          gist_title: asyncTraverseFolderList.js
          gist_description: asyncTraverseFolderList
          github_file: asyncTraverseFolderList.js
