# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: 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
          gist_url: https://gist.github.com/noiron/6cb7c92aa9e8c7bdd9b3268478f9acec
          gist_title: Example Gist Title
          gist_description: Example Gist Description
          github_file: traverseFolderList.js
