# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Gist
        uses: actions/checkout@v2
      
      - uses: exuanbo/actions-deploy-gist@v1.1.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: f6be6840739c7c0fc356659d64db96fc
          gist_description: traverseFolder
          gist_file_name: traverseFolderList.js
          file_path: traverseFolderList.js

      - uses: exuanbo/actions-deploy-gist@v1.1.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: f6be6840739c7c0fc356659d64db96fc
          gist_description: traverseFolder
          gist_file_name: asyncTraverseFolderList.js
          file_path: asyncTraverseFolderList.js

      - uses: exuanbo/actions-deploy-gist@v1.1.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: f6be6840739c7c0fc356659d64db96fc
          gist_description: traverseFolder
          file_path: traverseFolderObj.js

      - uses: exuanbo/actions-deploy-gist@v1.1.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: f6be6840739c7c0fc356659d64db96fc
          gist_description: traverseFolder
          file_path: index.js
      